services:

  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - dev-data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
     - app-network

  mysql-cli:
    image: mysql:8.4
    env_file:
      - .env
    command: mysql -hmysql -u$DB_USER -p$DB_PASSWORD $DB_DATABASE
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  flask:
    container_name: flask
    build: 
      context: ./backend
      args:
        - DEV=true
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: python main.py
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

volumes:
  dev-data:

networks:
  app-network:
    driver: bridge